name: CI

on: [push, pull_request]

env:
  TURSO_URL: "https://fake.com"
  TURSO_TOKEN: fake
  NEXT_PUBLIC_DISCORD_CLIENT_ID: "fake"
  DISCORD_CLIENT_SECRET: "fake"
  AUTH_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
