name: Cron Job

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST request
        env:
          CRON_API_KEY: ${{ secrets.CRON_API_KEY }}
        run: |
          curl -X POST https://viajesin.vercel.app/api/cron \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $CRON_API_KEY" \
          -d '{"action": "deleteGuestUser"}'
