name: Cron Job

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST request
        env:
          AUTH_URL: ${{ secrets.AUTH_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST $ENDPOINT_URL \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -d '{"action": "deleteGuestUser"}'
