name: Cron Job

on: [push, pull_request]

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST request
        env:
          ENDPOINT: ${{ secrets.ENDPOINT }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST "$ENDPOINT" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -d '{"action": "deleteGuestUser"}'
